/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OmaAmbulanceWlList {
    }
}
declare global {
    interface HTMLOmaAmbulanceWlListElement extends Components.OmaAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLOmaAmbulanceWlListElement: {
        prototype: HTMLOmaAmbulanceWlListElement;
        new (): HTMLOmaAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "oma-ambulance-wl-list": HTMLOmaAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface OmaAmbulanceWlList {
    }
    interface IntrinsicElements {
        "oma-ambulance-wl-list": OmaAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "oma-ambulance-wl-list": LocalJSX.OmaAmbulanceWlList & JSXBase.HTMLAttributes<HTMLOmaAmbulanceWlListElement>;
        }
    }
}
